using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace CarRental.WebApi.Data.Migrations
{
    [DbContext(typeof(RentalDbContext))]
    [Migration("20260403120000_FinalizeBreakingCleanupCanonicalSchema")]
    public partial class FinalizeBreakingCleanupCanonicalSchema : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "VehicleMakes"
                (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Name" character varying(60) NOT NULL,
                    "NormalizedName" character varying(60) NOT NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT NOW(),
                    "UpdatedAtUtc" timestamp with time zone NOT NULL DEFAULT NOW()
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_VehicleMakes_NormalizedName"
                    ON "VehicleMakes" ("NormalizedName");

                CREATE TABLE IF NOT EXISTS "VehicleModels"
                (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "MakeId" integer NOT NULL,
                    "Name" character varying(80) NOT NULL,
                    "NormalizedName" character varying(80) NOT NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT NOW(),
                    "UpdatedAtUtc" timestamp with time zone NOT NULL DEFAULT NOW()
                );

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname = 'FK_VehicleModels_VehicleMakes_MakeId') THEN
                        ALTER TABLE "VehicleModels"
                            ADD CONSTRAINT "FK_VehicleModels_VehicleMakes_MakeId"
                            FOREIGN KEY ("MakeId") REFERENCES "VehicleMakes" ("Id") ON DELETE CASCADE;
                    END IF;
                END $$;

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_VehicleModels_MakeId_NormalizedName"
                    ON "VehicleModels" ("MakeId", "NormalizedName");
                CREATE UNIQUE INDEX IF NOT EXISTS "AK_VehicleModels_Id_MakeId"
                    ON "VehicleModels" ("Id", "MakeId");
                """);

            migrationBuilder.Sql(
                """
                ALTER TABLE "Vehicles" ADD COLUMN IF NOT EXISTS "MakeId" integer;
                ALTER TABLE "Vehicles" ADD COLUMN IF NOT EXISTS "ModelId" integer;

                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'Vehicles' AND column_name = 'Make') THEN
                        INSERT INTO "VehicleMakes" ("Name", "NormalizedName", "CreatedAtUtc", "UpdatedAtUtc")
                        SELECT DISTINCT
                            btrim(v."Make"),
                            UPPER(regexp_replace(btrim(v."Make"), '\s+', ' ', 'g')),
                            NOW(),
                            NOW()
                        FROM "Vehicles" v
                        WHERE v."Make" IS NOT NULL
                          AND length(btrim(v."Make")) > 0
                          AND NOT EXISTS (
                              SELECT 1
                              FROM "VehicleMakes" vm
                              WHERE vm."NormalizedName" = UPPER(regexp_replace(btrim(v."Make"), '\s+', ' ', 'g')));

                        UPDATE "Vehicles" v
                        SET "MakeId" = vm."Id"
                        FROM "VehicleMakes" vm
                        WHERE v."MakeId" IS NULL
                          AND v."Make" IS NOT NULL
                          AND vm."NormalizedName" = UPPER(regexp_replace(btrim(v."Make"), '\s+', ' ', 'g'));
                    END IF;

                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'Vehicles' AND column_name = 'Model') THEN
                        INSERT INTO "VehicleModels" ("MakeId", "Name", "NormalizedName", "CreatedAtUtc", "UpdatedAtUtc")
                        SELECT DISTINCT
                            v."MakeId",
                            btrim(v."Model"),
                            UPPER(regexp_replace(btrim(v."Model"), '\s+', ' ', 'g')),
                            NOW(),
                            NOW()
                        FROM "Vehicles" v
                        WHERE v."MakeId" IS NOT NULL
                          AND v."Model" IS NOT NULL
                          AND length(btrim(v."Model")) > 0
                          AND NOT EXISTS (
                              SELECT 1
                              FROM "VehicleModels" md
                              WHERE md."MakeId" = v."MakeId"
                                AND md."NormalizedName" = UPPER(regexp_replace(btrim(v."Model"), '\s+', ' ', 'g')));

                        UPDATE "Vehicles" v
                        SET "ModelId" = md."Id"
                        FROM "VehicleModels" md
                        WHERE v."ModelId" IS NULL
                          AND v."MakeId" = md."MakeId"
                          AND v."Model" IS NOT NULL
                          AND md."NormalizedName" = UPPER(regexp_replace(btrim(v."Model"), '\s+', ' ', 'g'));
                    END IF;
                END $$;

                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM "Vehicles" WHERE "MakeId" IS NULL OR "ModelId" IS NULL) THEN
                        RAISE EXCEPTION 'Vehicles make/model backfill is incomplete. Canonical MakeId/ModelId are required.';
                    END IF;
                END $$;

                ALTER TABLE "Vehicles" ALTER COLUMN "MakeId" SET NOT NULL;
                ALTER TABLE "Vehicles" ALTER COLUMN "ModelId" SET NOT NULL;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_Vehicles_VehicleMakes_MakeId') THEN
                        ALTER TABLE "Vehicles"
                            ADD CONSTRAINT "FK_Vehicles_VehicleMakes_MakeId"
                            FOREIGN KEY ("MakeId") REFERENCES "VehicleMakes" ("Id") ON DELETE RESTRICT;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_Vehicles_VehicleModels_ModelId_MakeId') THEN
                        ALTER TABLE "Vehicles"
                            ADD CONSTRAINT "FK_Vehicles_VehicleModels_ModelId_MakeId"
                            FOREIGN KEY ("ModelId", "MakeId") REFERENCES "VehicleModels" ("Id", "MakeId") ON DELETE RESTRICT;
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS "IX_Vehicles_VehicleStatusCode_MakeId_ModelId"
                    ON "Vehicles" ("VehicleStatusCode", "MakeId", "ModelId");

                ALTER TABLE "Vehicles" DROP COLUMN IF EXISTS "Make";
                ALTER TABLE "Vehicles" DROP COLUMN IF EXISTS "Model";
                """);

            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'Rentals' AND column_name = 'Status') THEN
                        ALTER TABLE "Rentals" RENAME COLUMN "Status" TO "StatusId";
                    END IF;

                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'RentalInspections' AND column_name = 'Type') THEN
                        ALTER TABLE "RentalInspections" RENAME COLUMN "Type" TO "TypeId";
                    END IF;

                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'Payments' AND column_name = 'EmployeeId') THEN
                        ALTER TABLE "Payments" RENAME COLUMN "EmployeeId" TO "RecordedByEmployeeId";
                    END IF;

                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'Payments' AND column_name = 'Method') THEN
                        ALTER TABLE "Payments" RENAME COLUMN "Method" TO "MethodId";
                    END IF;

                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'Payments' AND column_name = 'Direction') THEN
                        ALTER TABLE "Payments" RENAME COLUMN "Direction" TO "DirectionId";
                    END IF;

                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'Payments' AND column_name = 'Status') THEN
                        ALTER TABLE "Payments" RENAME COLUMN "Status" TO "StatusId";
                    END IF;

                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'Damages' AND column_name = 'ActNumber') THEN
                        ALTER TABLE "Damages" RENAME COLUMN "ActNumber" TO "DamageActNumber";
                    END IF;

                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'Damages' AND column_name = 'Status') THEN
                        ALTER TABLE "Damages" RENAME COLUMN "Status" TO "StatusId";
                    END IF;
                END $$;

                ALTER TABLE "Rentals" ALTER COLUMN "CreatedByEmployeeId" DROP NOT NULL;
                ALTER TABLE "Payments" ALTER COLUMN "RecordedByEmployeeId" DROP NOT NULL;

                ALTER TABLE "Rentals" DROP CONSTRAINT IF EXISTS "CK_Rentals_DateRange";
                ALTER TABLE "Rentals"
                    ADD CONSTRAINT "CK_Rentals_DateRange"
                    CHECK ("StartDate" < "EndDate");
                """);

            migrationBuilder.Sql(
                """
                ALTER TABLE "Clients" ADD COLUMN IF NOT EXISTS "BlacklistedByEmployeeId" integer;

                UPDATE "Clients" c
                SET "BlacklistedByEmployeeId" = seed."Id",
                    "BlacklistedAtUtc" = COALESCE(c."BlacklistedAtUtc", c."UpdatedAtUtc", c."CreatedAtUtc", NOW()),
                    "BlacklistReason" = CASE
                        WHEN length(btrim(COALESCE(c."BlacklistReason", ''))) > 0 THEN btrim(c."BlacklistReason")
                        ELSE 'Legacy blacklist backfill.'
                    END
                FROM (
                    SELECT e."Id"
                    FROM "Employees" e
                    ORDER BY e."CreatedAtUtc", e."Id"
                    LIMIT 1
                ) AS seed
                WHERE c."IsBlacklisted" = TRUE
                  AND c."BlacklistedByEmployeeId" IS NULL;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_Clients_Employees_BlacklistedByEmployeeId') THEN
                        ALTER TABLE "Clients"
                            ADD CONSTRAINT "FK_Clients_Employees_BlacklistedByEmployeeId"
                            FOREIGN KEY ("BlacklistedByEmployeeId") REFERENCES "Employees" ("Id") ON DELETE RESTRICT;
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS "IX_Clients_BlacklistedByEmployeeId"
                    ON "Clients" ("BlacklistedByEmployeeId");

                ALTER TABLE "Clients" DROP CONSTRAINT IF EXISTS "CK_Clients_Blacklist_Consistency";
                ALTER TABLE "Clients"
                    ADD CONSTRAINT "CK_Clients_Blacklist_Consistency"
                    CHECK (
                        (NOT "IsBlacklisted" AND "BlacklistReason" IS NULL AND "BlacklistedAtUtc" IS NULL AND "BlacklistedByEmployeeId" IS NULL)
                        OR
                        ("IsBlacklisted" AND length(btrim(COALESCE("BlacklistReason", ''))) > 0 AND "BlacklistedAtUtc" IS NOT NULL AND "BlacklistedByEmployeeId" IS NOT NULL)
                    );
                """);

            migrationBuilder.Sql(
                """
                ALTER TABLE "MaintenanceRecords" ADD COLUMN IF NOT EXISTS "NextServiceDate" date;

                UPDATE "MaintenanceRecords"
                SET "ServiceProviderName" = NULL
                WHERE length(btrim(COALESCE("ServiceProviderName", ''))) = 0;

                UPDATE "MaintenanceRecords"
                SET "ServiceProviderName" = btrim("ServiceProviderName")
                WHERE "ServiceProviderName" IS NOT NULL;

                UPDATE "MaintenanceRecords"
                SET "ServiceProviderName" = 'Legacy maintenance backfill'
                WHERE "PerformedByEmployeeId" IS NULL
                  AND "ServiceProviderName" IS NULL;

                UPDATE "MaintenanceRecords"
                SET "ServiceProviderName" = NULL
                WHERE "PerformedByEmployeeId" IS NOT NULL
                  AND "ServiceProviderName" IS NOT NULL;

                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public'
                          AND table_name = 'MaintenanceRecords'
                          AND column_name = 'ServiceDate'
                          AND data_type <> 'date') THEN
                        ALTER TABLE "MaintenanceRecords"
                            ALTER COLUMN "ServiceDate" TYPE date
                            USING "ServiceDate"::date;
                    END IF;
                END $$;

                ALTER TABLE "MaintenanceRecords" ALTER COLUMN "NextServiceMileage" DROP NOT NULL;

                ALTER TABLE "MaintenanceRecords" DROP CONSTRAINT IF EXISTS "CK_MaintenanceRecords_NextServiceMileage_GteCurrent";
                ALTER TABLE "MaintenanceRecords" DROP CONSTRAINT IF EXISTS "CK_MaintenanceRecords_NextServiceMileage_Positive";
                ALTER TABLE "MaintenanceRecords" DROP CONSTRAINT IF EXISTS "CK_MaintenanceRecords_NextService_Planning";
                ALTER TABLE "MaintenanceRecords" DROP CONSTRAINT IF EXISTS "CK_MaintenanceRecords_ServiceActor_Xor";

                ALTER TABLE "MaintenanceRecords"
                    ADD CONSTRAINT "CK_MaintenanceRecords_NextServiceMileage_Positive"
                    CHECK ("NextServiceMileage" IS NULL OR "NextServiceMileage" > 0);
                ALTER TABLE "MaintenanceRecords"
                    ADD CONSTRAINT "CK_MaintenanceRecords_NextServiceMileage_GteCurrent"
                    CHECK ("NextServiceMileage" IS NULL OR "NextServiceMileage" >= "MileageAtService");
                ALTER TABLE "MaintenanceRecords"
                    ADD CONSTRAINT "CK_MaintenanceRecords_NextService_Planning"
                    CHECK ("NextServiceMileage" IS NOT NULL OR "NextServiceDate" IS NOT NULL);
                ALTER TABLE "MaintenanceRecords"
                    ADD CONSTRAINT "CK_MaintenanceRecords_ServiceActor_Xor"
                    CHECK (
                        ("PerformedByEmployeeId" IS NOT NULL AND length(btrim(COALESCE("ServiceProviderName", ''))) = 0)
                        OR
                        ("PerformedByEmployeeId" IS NULL AND length(btrim(COALESCE("ServiceProviderName", ''))) > 0)
                    );
                """);

            migrationBuilder.Sql(
                """
                ALTER TABLE "VehiclePhotos" ADD COLUMN IF NOT EXISTS "UpdatedAtUtc" timestamp with time zone;
                ALTER TABLE "VehiclePhotos" ADD COLUMN IF NOT EXISTS "IsDeleted" boolean NOT NULL DEFAULT FALSE;
                UPDATE "VehiclePhotos" SET "UpdatedAtUtc" = COALESCE("UpdatedAtUtc", "CreatedAtUtc", NOW()) WHERE "UpdatedAtUtc" IS NULL;
                ALTER TABLE "VehiclePhotos" ALTER COLUMN "UpdatedAtUtc" SET NOT NULL;
                DROP INDEX IF EXISTS "IX_VehiclePhotos_VehicleId_SortOrder";
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_VehiclePhotos_VehicleId_SortOrder"
                    ON "VehiclePhotos" ("VehicleId", "SortOrder")
                    WHERE "IsDeleted" = FALSE;

                ALTER TABLE "DamagePhotos" ADD COLUMN IF NOT EXISTS "UpdatedAtUtc" timestamp with time zone;
                ALTER TABLE "DamagePhotos" ADD COLUMN IF NOT EXISTS "IsDeleted" boolean NOT NULL DEFAULT FALSE;
                UPDATE "DamagePhotos" SET "UpdatedAtUtc" = COALESCE("UpdatedAtUtc", "CreatedAtUtc", NOW()) WHERE "UpdatedAtUtc" IS NULL;
                ALTER TABLE "DamagePhotos" ALTER COLUMN "UpdatedAtUtc" SET NOT NULL;
                DROP INDEX IF EXISTS "IX_DamagePhotos_DamageId_SortOrder";
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_DamagePhotos_DamageId_SortOrder"
                    ON "DamagePhotos" ("DamageId", "SortOrder")
                    WHERE "IsDeleted" = FALSE;
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "RentalStatusHistory"
                (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "RentalId" integer NOT NULL,
                    "FromStatusId" integer NULL,
                    "ToStatusId" integer NOT NULL,
                    "ChangedAtUtc" timestamp with time zone NOT NULL,
                    "ChangedByEmployeeId" integer NULL,
                    "ChangedBySource" character varying(16) NOT NULL
                );

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_RentalStatusHistory_Rentals_RentalId') THEN
                        ALTER TABLE "RentalStatusHistory"
                            ADD CONSTRAINT "FK_RentalStatusHistory_Rentals_RentalId"
                            FOREIGN KEY ("RentalId") REFERENCES "Rentals" ("Id") ON DELETE CASCADE;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_RentalStatusHistory_Employees_ChangedByEmployeeId') THEN
                        ALTER TABLE "RentalStatusHistory"
                            ADD CONSTRAINT "FK_RentalStatusHistory_Employees_ChangedByEmployeeId"
                            FOREIGN KEY ("ChangedByEmployeeId") REFERENCES "Employees" ("Id") ON DELETE RESTRICT;
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS "IX_RentalStatusHistory_RentalId_ChangedAtUtc"
                    ON "RentalStatusHistory" ("RentalId", "ChangedAtUtc");

                ALTER TABLE "RentalStatusHistory" DROP CONSTRAINT IF EXISTS "CK_RentalStatusHistory_Source_Allowed";
                ALTER TABLE "RentalStatusHistory"
                    ADD CONSTRAINT "CK_RentalStatusHistory_Source_Allowed"
                    CHECK ("ChangedBySource" IN ('EMPLOYEE', 'CLIENT', 'SYSTEM'));

                INSERT INTO "RentalStatusHistory" ("RentalId", "FromStatusId", "ToStatusId", "ChangedAtUtc", "ChangedByEmployeeId", "ChangedBySource")
                SELECT
                    r."Id",
                    NULL,
                    r."StatusId",
                    COALESCE(r."CanceledAtUtc", r."ClosedAtUtc", r."CreatedAtUtc"),
                    COALESCE(r."ClosedByEmployeeId", r."CanceledByEmployeeId", r."CreatedByEmployeeId"),
                    CASE
                        WHEN COALESCE(r."ClosedByEmployeeId", r."CanceledByEmployeeId", r."CreatedByEmployeeId") IS NOT NULL THEN 'EMPLOYEE'
                        ELSE 'CLIENT'
                    END
                FROM "Rentals" r
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM "RentalStatusHistory" h
                    WHERE h."RentalId" = r."Id");

                CREATE TABLE IF NOT EXISTS "DamageStatusHistory"
                (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "DamageId" integer NOT NULL,
                    "FromStatusId" integer NULL,
                    "ToStatusId" integer NOT NULL,
                    "ChangedAtUtc" timestamp with time zone NOT NULL,
                    "ChangedByEmployeeId" integer NULL,
                    "ChangedBySource" character varying(16) NOT NULL
                );

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_DamageStatusHistory_Damages_DamageId') THEN
                        ALTER TABLE "DamageStatusHistory"
                            ADD CONSTRAINT "FK_DamageStatusHistory_Damages_DamageId"
                            FOREIGN KEY ("DamageId") REFERENCES "Damages" ("Id") ON DELETE CASCADE;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'FK_DamageStatusHistory_Employees_ChangedByEmployeeId') THEN
                        ALTER TABLE "DamageStatusHistory"
                            ADD CONSTRAINT "FK_DamageStatusHistory_Employees_ChangedByEmployeeId"
                            FOREIGN KEY ("ChangedByEmployeeId") REFERENCES "Employees" ("Id") ON DELETE RESTRICT;
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS "IX_DamageStatusHistory_DamageId_ChangedAtUtc"
                    ON "DamageStatusHistory" ("DamageId", "ChangedAtUtc");

                ALTER TABLE "DamageStatusHistory" DROP CONSTRAINT IF EXISTS "CK_DamageStatusHistory_Source_Allowed";
                ALTER TABLE "DamageStatusHistory"
                    ADD CONSTRAINT "CK_DamageStatusHistory_Source_Allowed"
                    CHECK ("ChangedBySource" IN ('EMPLOYEE', 'CLIENT', 'SYSTEM'));

                INSERT INTO "DamageStatusHistory" ("DamageId", "FromStatusId", "ToStatusId", "ChangedAtUtc", "ChangedByEmployeeId", "ChangedBySource")
                SELECT
                    d."Id",
                    NULL,
                    d."StatusId",
                    COALESCE(d."UpdatedAtUtc", d."CreatedAtUtc", NOW()),
                    d."ReportedByEmployeeId",
                    CASE WHEN d."ReportedByEmployeeId" IS NOT NULL THEN 'EMPLOYEE' ELSE 'SYSTEM' END
                FROM "Damages" d
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM "DamageStatusHistory" h
                    WHERE h."DamageId" = d."Id");
                """);

            migrationBuilder.Sql(
                """
                CREATE OR REPLACE FUNCTION enforce_account_exclusivity() RETURNS trigger AS $$
                BEGIN
                    IF NEW."AccountId" IS NULL THEN
                        RETURN NEW;
                    END IF;

                    IF TG_TABLE_NAME = 'Clients' THEN
                        IF EXISTS (SELECT 1 FROM "Employees" WHERE "AccountId" = NEW."AccountId") THEN
                            RAISE EXCEPTION 'AccountId % cannot be assigned to both Clients and Employees.', NEW."AccountId";
                        END IF;
                    ELSE
                        IF EXISTS (SELECT 1 FROM "Clients" WHERE "AccountId" = NEW."AccountId") THEN
                            RAISE EXCEPTION 'AccountId % cannot be assigned to both Clients and Employees.', NEW."AccountId";
                        END IF;
                    END IF;

                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                DROP TRIGGER IF EXISTS trg_clients_account_exclusivity ON "Clients";
                CREATE TRIGGER trg_clients_account_exclusivity
                    BEFORE INSERT OR UPDATE OF "AccountId"
                    ON "Clients"
                    FOR EACH ROW
                    EXECUTE FUNCTION enforce_account_exclusivity();

                DROP TRIGGER IF EXISTS trg_employees_account_exclusivity ON "Employees";
                CREATE TRIGGER trg_employees_account_exclusivity
                    BEFORE INSERT OR UPDATE OF "AccountId"
                    ON "Employees"
                    FOR EACH ROW
                    EXECUTE FUNCTION enforce_account_exclusivity();
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DROP TRIGGER IF EXISTS trg_clients_account_exclusivity ON "Clients";
                DROP TRIGGER IF EXISTS trg_employees_account_exclusivity ON "Employees";
                DROP FUNCTION IF EXISTS enforce_account_exclusivity();
                """);
        }
    }
}
