// <auto-generated />
using System;
using CarRental.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarRental.WebApi.Data.Migrations
{
    [DbContext(typeof(RentalDbContext))]
    partial class RentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarRental.WebApi.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("PasswordChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Accounts", t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_FailedLoginAttempts_NonNegative", "\"FailedLoginAttempts\" >= 0");
                        });
                });

            modelBuilder.Entity("CarRental.WebApi.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("BlacklistReason")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime?>("BlacklistedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsBlacklisted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.ClientDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("DocumentTypeCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("StoredPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "DocumentTypeCode")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.HasIndex("DocumentTypeCode", "DocumentNumber")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("ClientDocuments");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.ClientDocumentTypeLookup", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Code");

                    b.ToTable("ClientDocumentTypes");

                    b.HasData(
                        new
                        {
                            Code = "PASSPORT",
                            DisplayName = "Passport"
                        },
                        new
                        {
                            Code = "DRIVER_LICENSE",
                            DisplayName = "Driver license"
                        });
                });

            modelBuilder.Entity("CarRental.WebApi.Models.ContractSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LastNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("ContractSequences");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.Damage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<decimal>("ChargedAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateReported")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("RentalId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RepairCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ReportedByEmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActNumber")
                        .IsUnique();

                    b.HasIndex("RentalId");

                    b.HasIndex("ReportedByEmployeeId");

                    b.HasIndex("Status");

                    b.HasIndex("RentalId", "VehicleId");

                    b.HasIndex("VehicleId", "DateReported");

                    b.ToTable("Damages", t =>
                        {
                            t.HasCheckConstraint("CK_Damages_ChargedAmount_LteRepairCost", "\"ChargedAmount\" <= \"RepairCost\"");

                            t.HasCheckConstraint("CK_Damages_ChargedAmount_NonNegative", "\"ChargedAmount\" >= 0");

                            t.HasCheckConstraint("CK_Damages_RepairCost_Positive", "\"RepairCost\" > 0");

                            t.HasCheckConstraint("CK_Damages_Status_ChargeConsistency", "(\"Status\" <> 1 OR \"ChargedAmount\" = 0) AND (\"Status\" <> 2 OR \"ChargedAmount\" > 0)");
                        });
                });

            modelBuilder.Entity("CarRental.WebApi.Models.DamagePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DamageId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DamageId", "SortOrder")
                        .IsUnique();

                    b.ToTable("DamagePhotos");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.DamageStatusLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.ToTable("DamageStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Open"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Charged"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Resolved"
                        });
                });

            modelBuilder.Entity("CarRental.WebApi.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Role", "FullName");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.EmployeeRoleLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "User"
                        });
                });

            modelBuilder.Entity("CarRental.WebApi.Models.FuelTypeLookup", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Code");

                    b.ToTable("FuelTypes");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.InspectionTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.ToTable("InspectionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Pickup"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Return"
                        });
                });

            modelBuilder.Entity("CarRental.WebApi.Models.MaintenanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MaintenanceTypeCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("MileageAtService")
                        .HasColumnType("integer");

                    b.Property<int>("NextServiceMileage")
                        .HasColumnType("integer");

                    b.Property<int?>("PerformedByEmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ServiceProviderName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceTypeCode");

                    b.HasIndex("PerformedByEmployeeId");

                    b.HasIndex("VehicleId", "ServiceDate");

                    b.ToTable("MaintenanceRecords", t =>
                        {
                            t.HasCheckConstraint("CK_MaintenanceRecords_Cost_NonNegative", "\"Cost\" >= 0");

                            t.HasCheckConstraint("CK_MaintenanceRecords_MileageAtService_NonNegative", "\"MileageAtService\" >= 0");

                            t.HasCheckConstraint("CK_MaintenanceRecords_NextServiceMileage_GteCurrent", "\"NextServiceMileage\" >= \"MileageAtService\"");

                            t.HasCheckConstraint("CK_MaintenanceRecords_NextServiceMileage_Positive", "\"NextServiceMileage\" > 0");
                        });
                });

            modelBuilder.Entity("CarRental.WebApi.Models.MaintenanceTypeLookup", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Code");

                    b.ToTable("MaintenanceTypes");

                    b.HasData(
                        new
                        {
                            Code = "SCHEDULED",
                            DisplayName = "Scheduled service"
                        },
                        new
                        {
                            Code = "REPAIR",
                            DisplayName = "Repair"
                        },
                        new
                        {
                            Code = "TIRES",
                            DisplayName = "Tires"
                        },
                        new
                        {
                            Code = "INSPECTION",
                            DisplayName = "Inspection"
                        });
                });

            modelBuilder.Entity("CarRental.WebApi.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalTransactionId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("RentalId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Direction");

                    b.HasIndex("ExternalTransactionId")
                        .IsUnique();

                    b.HasIndex("Method");

                    b.HasIndex("Status");

                    b.HasIndex("EmployeeId", "CreatedAtUtc");

                    b.HasIndex("RentalId", "CreatedAtUtc");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount_Positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("CarRental.WebApi.Models.PaymentDirectionLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.ToTable("PaymentDirections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Incoming"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Refund"
                        });
                });

            modelBuilder.Entity("CarRental.WebApi.Models.PaymentMethodLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Cash"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Card"
                        });
                });

            modelBuilder.Entity("CarRental.WebApi.Models.PaymentStatusLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.ToTable("PaymentStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Canceled"
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "Refunded"
                        });
                });

            modelBuilder.Entity("CarRental.WebApi.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CanceledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CanceledByEmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ClosedByEmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByEmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("EndMileage")
                        .HasColumnType("integer");

                    b.Property<decimal>("OverageFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ReturnLocation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("StartMileage")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CanceledByEmployeeId");

                    b.HasIndex("ClosedByEmployeeId");

                    b.HasIndex("ContractNumber")
                        .IsUnique();

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("ClientId", "Status");

                    b.HasIndex("CreatedByEmployeeId", "CreatedAtUtc");

                    b.HasIndex("VehicleId", "StartDate", "EndDate", "Status");

                    b.ToTable("Rentals", t =>
                        {
                            t.HasCheckConstraint("CK_Rentals_Canceled_Lifecycle", "\"Status\" <> 4 OR (\"ClosedAtUtc\" IS NULL AND \"CanceledAtUtc\" IS NOT NULL AND length(btrim(COALESCE(\"CancellationReason\", ''))) > 0)");

                            t.HasCheckConstraint("CK_Rentals_Closed_Lifecycle", "\"Status\" <> 3 OR (\"ClosedAtUtc\" IS NOT NULL AND \"CanceledAtUtc\" IS NULL AND \"CancellationReason\" IS NULL)");

                            t.HasCheckConstraint("CK_Rentals_DateRange", "\"StartDate\" <= \"EndDate\"");

                            t.HasCheckConstraint("CK_Rentals_EndMileage_Valid", "\"EndMileage\" IS NULL OR \"EndMileage\" >= \"StartMileage\"");

                            t.HasCheckConstraint("CK_Rentals_Open_Lifecycle", "\"Status\" IN (3, 4) OR (\"ClosedAtUtc\" IS NULL AND \"CanceledAtUtc\" IS NULL AND \"CancellationReason\" IS NULL)");

                            t.HasCheckConstraint("CK_Rentals_OverageFee_NonNegative", "\"OverageFee\" >= 0");

                            t.HasCheckConstraint("CK_Rentals_StartMileage_NonNegative", "\"StartMileage\" >= 0");

                            t.HasCheckConstraint("CK_Rentals_TotalAmount_NonNegative", "\"TotalAmount\" >= 0");
                        });
                });

            modelBuilder.Entity("CarRental.WebApi.Models.RentalInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FuelPercent")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PerformedByEmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("RentalId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByEmployeeId");

                    b.HasIndex("Type");

                    b.HasIndex("RentalId", "Type")
                        .IsUnique();

                    b.ToTable("RentalInspections", t =>
                        {
                            t.HasCheckConstraint("CK_RentalInspections_FuelPercent_Range", "\"FuelPercent\" IS NULL OR \"FuelPercent\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("CarRental.WebApi.Models.RentalStatusLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.ToTable("RentalStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Booked"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Active"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Closed"
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "Canceled"
                        });
                });

            modelBuilder.Entity("CarRental.WebApi.Models.TransmissionTypeLookup", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Code");

                    b.ToTable("TransmissionTypes");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CargoCapacityUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("CargoCapacityValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("ConsumptionUnit")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<decimal>("ConsumptionValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DailyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("DoorsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4);

                    b.Property<string>("FuelTypeCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("");

                    b.Property<bool>("HasAirConditioning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PowertrainCapacityUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("PowertrainCapacityValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ServiceIntervalKm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10000);

                    b.Property<string>("TransmissionTypeCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleStatusCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("READY");

                    b.HasKey("Id");

                    b.HasIndex("FuelTypeCode");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LicensePlate")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.HasIndex("TransmissionTypeCode");

                    b.HasIndex("VehicleStatusCode", "Make", "Model");

                    b.ToTable("Vehicles", t =>
                        {
                            t.HasCheckConstraint("CK_Vehicles_CargoCapacityUnit_Allowed", "\"CargoCapacityUnit\" IN ('L', 'KG', 'SEATS')");

                            t.HasCheckConstraint("CK_Vehicles_CargoCapacity_Positive", "\"CargoCapacityValue\" > 0");

                            t.HasCheckConstraint("CK_Vehicles_ConsumptionUnit_Allowed", "\"ConsumptionUnit\" IN ('L_PER_100KM', 'KWH_PER_100KM')");

                            t.HasCheckConstraint("CK_Vehicles_Consumption_Positive", "\"ConsumptionValue\" > 0");

                            t.HasCheckConstraint("CK_Vehicles_DailyRate_Positive", "\"DailyRate\" > 0");

                            t.HasCheckConstraint("CK_Vehicles_DoorsCount_Range", "\"DoorsCount\" BETWEEN 1 AND 8");

                            t.HasCheckConstraint("CK_Vehicles_Mileage_NonNegative", "\"Mileage\" >= 0");

                            t.HasCheckConstraint("CK_Vehicles_PowertrainCapacityUnit_Allowed", "\"PowertrainCapacityUnit\" IN ('L', 'KWH')");

                            t.HasCheckConstraint("CK_Vehicles_PowertrainCapacity_Positive", "\"PowertrainCapacityValue\" > 0");

                            t.HasCheckConstraint("CK_Vehicles_ServiceIntervalKm_Positive", "\"ServiceIntervalKm\" > 0");
                        });
                });

            modelBuilder.Entity("CarRental.WebApi.Models.VehiclePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "SortOrder")
                        .IsUnique();

                    b.ToTable("VehiclePhotos");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.VehicleStatusLookup", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Code");

                    b.ToTable("VehicleStatuses");

                    b.HasData(
                        new
                        {
                            Code = "READY",
                            DisplayName = "Ready"
                        },
                        new
                        {
                            Code = "RENTED",
                            DisplayName = "Rented"
                        },
                        new
                        {
                            Code = "MAINTENANCE",
                            DisplayName = "Maintenance"
                        },
                        new
                        {
                            Code = "DAMAGED",
                            DisplayName = "Damaged"
                        },
                        new
                        {
                            Code = "INACTIVE",
                            DisplayName = "Inactive"
                        });
                });

            modelBuilder.Entity("CarRental.WebApi.Models.Client", b =>
                {
                    b.HasOne("CarRental.WebApi.Models.Account", "Account")
                        .WithOne("Client")
                        .HasForeignKey("CarRental.WebApi.Models.Client", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.ClientDocument", b =>
                {
                    b.HasOne("CarRental.WebApi.Models.Client", "Client")
                        .WithMany("Documents")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRental.WebApi.Models.ClientDocumentTypeLookup", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.Damage", b =>
                {
                    b.HasOne("CarRental.WebApi.Models.Employee", "ReportedByEmployee")
                        .WithMany("ReportedDamages")
                        .HasForeignKey("ReportedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.WebApi.Models.DamageStatusLookup", "StatusLookup")
                        .WithMany("Damages")
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.WebApi.Models.Vehicle", "Vehicle")
                        .WithMany("Damages")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRental.WebApi.Models.Rental", "Rental")
                        .WithMany("Damages")
                        .HasForeignKey("RentalId", "VehicleId")
                        .HasPrincipalKey("Id", "VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Rental");

                    b.Navigation("ReportedByEmployee");

                    b.Navigation("StatusLookup");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.DamagePhoto", b =>
                {
                    b.HasOne("CarRental.WebApi.Models.Damage", "Damage")
                        .WithMany("Photos")
                        .HasForeignKey("DamageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Damage");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.Employee", b =>
                {
                    b.HasOne("CarRental.WebApi.Models.Account", "Account")
                        .WithOne("Employee")
                        .HasForeignKey("CarRental.WebApi.Models.Employee", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.WebApi.Models.EmployeeRoleLookup", "RoleLookup")
                        .WithMany("Employees")
                        .HasForeignKey("Role")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("RoleLookup");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.MaintenanceRecord", b =>
                {
                    b.HasOne("CarRental.WebApi.Models.MaintenanceTypeLookup", "MaintenanceType")
                        .WithMany("Records")
                        .HasForeignKey("MaintenanceTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.WebApi.Models.Employee", "PerformedByEmployee")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("PerformedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarRental.WebApi.Models.Vehicle", "Vehicle")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaintenanceType");

                    b.Navigation("PerformedByEmployee");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.Payment", b =>
                {
                    b.HasOne("CarRental.WebApi.Models.PaymentDirectionLookup", "DirectionLookup")
                        .WithMany("Payments")
                        .HasForeignKey("Direction")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.WebApi.Models.Employee", "Employee")
                        .WithMany("Payments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.WebApi.Models.PaymentMethodLookup", "MethodLookup")
                        .WithMany("Payments")
                        .HasForeignKey("Method")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.WebApi.Models.Rental", "Rental")
                        .WithMany("Payments")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRental.WebApi.Models.PaymentStatusLookup", "StatusLookup")
                        .WithMany("Payments")
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DirectionLookup");

                    b.Navigation("Employee");

                    b.Navigation("MethodLookup");

                    b.Navigation("Rental");

                    b.Navigation("StatusLookup");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.Rental", b =>
                {
                    b.HasOne("CarRental.WebApi.Models.Employee", "CanceledByEmployee")
                        .WithMany("CanceledRentals")
                        .HasForeignKey("CanceledByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarRental.WebApi.Models.Client", "Client")
                        .WithMany("Rentals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.WebApi.Models.Employee", "ClosedByEmployee")
                        .WithMany("ClosedRentals")
                        .HasForeignKey("ClosedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarRental.WebApi.Models.Employee", "CreatedByEmployee")
                        .WithMany("CreatedRentals")
                        .HasForeignKey("CreatedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.WebApi.Models.RentalStatusLookup", "StatusLookup")
                        .WithMany("Rentals")
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.WebApi.Models.Vehicle", "Vehicle")
                        .WithMany("Rentals")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanceledByEmployee");

                    b.Navigation("Client");

                    b.Navigation("ClosedByEmployee");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("StatusLookup");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.RentalInspection", b =>
                {
                    b.HasOne("CarRental.WebApi.Models.Employee", "PerformedByEmployee")
                        .WithMany("Inspections")
                        .HasForeignKey("PerformedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.WebApi.Models.Rental", "Rental")
                        .WithMany("Inspections")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRental.WebApi.Models.InspectionTypeLookup", "TypeLookup")
                        .WithMany("Inspections")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerformedByEmployee");

                    b.Navigation("Rental");

                    b.Navigation("TypeLookup");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.Vehicle", b =>
                {
                    b.HasOne("CarRental.WebApi.Models.FuelTypeLookup", "FuelTypeLookup")
                        .WithMany("Vehicles")
                        .HasForeignKey("FuelTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.WebApi.Models.TransmissionTypeLookup", "TransmissionTypeLookup")
                        .WithMany("Vehicles")
                        .HasForeignKey("TransmissionTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.WebApi.Models.VehicleStatusLookup", "VehicleStatus")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleStatusCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FuelTypeLookup");

                    b.Navigation("TransmissionTypeLookup");

                    b.Navigation("VehicleStatus");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.VehiclePhoto", b =>
                {
                    b.HasOne("CarRental.WebApi.Models.Vehicle", "Vehicle")
                        .WithMany("Photos")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.Account", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.Client", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.ClientDocumentTypeLookup", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.Damage", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.DamageStatusLookup", b =>
                {
                    b.Navigation("Damages");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.Employee", b =>
                {
                    b.Navigation("CanceledRentals");

                    b.Navigation("ClosedRentals");

                    b.Navigation("CreatedRentals");

                    b.Navigation("Inspections");

                    b.Navigation("MaintenanceRecords");

                    b.Navigation("Payments");

                    b.Navigation("ReportedDamages");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.EmployeeRoleLookup", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.FuelTypeLookup", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.InspectionTypeLookup", b =>
                {
                    b.Navigation("Inspections");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.MaintenanceTypeLookup", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.PaymentDirectionLookup", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.PaymentMethodLookup", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.PaymentStatusLookup", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.Rental", b =>
                {
                    b.Navigation("Damages");

                    b.Navigation("Inspections");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.RentalStatusLookup", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.TransmissionTypeLookup", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.Vehicle", b =>
                {
                    b.Navigation("Damages");

                    b.Navigation("MaintenanceRecords");

                    b.Navigation("Photos");

                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("CarRental.WebApi.Models.VehicleStatusLookup", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
