-- PostgreSQL schema for coursework defense
-- Run on empty database

CREATE TABLE IF NOT EXISTS "Employees" (
    "Id"              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FullName"        varchar(120) NOT NULL,
    "Login"           varchar(60) NOT NULL UNIQUE,
    "PasswordHash"    varchar(512) NOT NULL,
    "Role"            integer NOT NULL,
    "IsActive"        boolean NOT NULL DEFAULT TRUE,
    "FailedLoginAttempts" integer NOT NULL DEFAULT 0,
    "LockoutUntilUtc" timestamptz NULL,
    "LastLoginUtc"    timestamptz NULL,
    "PasswordChangedAtUtc" timestamptz NOT NULL,
    CONSTRAINT "CK_Employees_Role_Range" CHECK ("Role" BETWEEN 1 AND 3),
    CONSTRAINT "CK_Employees_FailedLoginAttempts_NonNegative" CHECK ("FailedLoginAttempts" >= 0)
);

CREATE TABLE IF NOT EXISTS "Clients" (
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FullName"      varchar(120) NOT NULL,
    "PassportData"  varchar(120) NOT NULL,
    "DriverLicense" varchar(80) NOT NULL UNIQUE,
    "Phone"         varchar(40) NOT NULL,
    "Blacklisted"   boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS "Vehicles" (
    "Id"              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Make"            varchar(60) NOT NULL,
    "Model"           varchar(80) NOT NULL,
    "LicensePlate"    varchar(30) NOT NULL UNIQUE,
    "Mileage"         integer NOT NULL,
    "DailyRate"       numeric(10,2) NOT NULL,
    "IsAvailable"     boolean NOT NULL,
    "ServiceIntervalKm" integer NOT NULL DEFAULT 10000,
    "PhotoPath"       varchar(500) NULL,
    CONSTRAINT "CK_Vehicles_Mileage_NonNegative" CHECK ("Mileage" >= 0),
    CONSTRAINT "CK_Vehicles_DailyRate_Positive" CHECK ("DailyRate" > 0),
    CONSTRAINT "CK_Vehicles_ServiceIntervalKm_Positive" CHECK ("ServiceIntervalKm" > 0)
);

CREATE TABLE IF NOT EXISTS "ContractSequences" (
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Year"       integer NOT NULL UNIQUE,
    "LastNumber" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "Rentals" (
    "Id"               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClientId"         integer NOT NULL REFERENCES "Clients"("Id") ON DELETE RESTRICT,
    "VehicleId"        integer NOT NULL REFERENCES "Vehicles"("Id") ON DELETE RESTRICT,
    "EmployeeId"       integer NOT NULL REFERENCES "Employees"("Id") ON DELETE RESTRICT,
    "ContractNumber"   varchar(40) NOT NULL UNIQUE,
    "StartDate"        timestamptz NOT NULL,
    "EndDate"          timestamptz NOT NULL,
    "StartMileage"     integer NOT NULL,
    "EndMileage"       integer NULL,
    "OverageFee"       numeric(10,2) NOT NULL,
    "TotalAmount"      numeric(10,2) NOT NULL,
    "IsClosed"         boolean NOT NULL,
    "Status"           integer NOT NULL,
    "CreatedAtUtc"     timestamptz NOT NULL,
    "ClosedAtUtc"      timestamptz NULL,
    "CanceledAtUtc"    timestamptz NULL,
    "CancellationReason" varchar(400) NULL,
    CONSTRAINT "CK_Rentals_DateRange" CHECK ("StartDate" <= "EndDate"),
    CONSTRAINT "CK_Rentals_StartMileage_NonNegative" CHECK ("StartMileage" >= 0),
    CONSTRAINT "CK_Rentals_EndMileage_Valid" CHECK ("EndMileage" IS NULL OR "EndMileage" >= "StartMileage"),
    CONSTRAINT "CK_Rentals_OverageFee_NonNegative" CHECK ("OverageFee" >= 0),
    CONSTRAINT "CK_Rentals_TotalAmount_NonNegative" CHECK ("TotalAmount" >= 0),
    CONSTRAINT "CK_Rentals_Status_Range" CHECK ("Status" BETWEEN 1 AND 4),
    CONSTRAINT "CK_Rentals_IsClosed_MatchesStatus" CHECK (("Status" = 3) = "IsClosed")
);

CREATE TABLE IF NOT EXISTS "Payments" (
    "Id"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RentalId"     integer NOT NULL REFERENCES "Rentals"("Id") ON DELETE CASCADE,
    "EmployeeId"   integer NOT NULL REFERENCES "Employees"("Id") ON DELETE RESTRICT,
    "Amount"       numeric(10,2) NOT NULL,
    "Method"       integer NOT NULL,
    "Direction"    integer NOT NULL,
    "CreatedAtUtc" timestamptz NOT NULL,
    "Notes"        varchar(300) NOT NULL,
    CONSTRAINT "CK_Payments_Amount_Positive" CHECK ("Amount" > 0),
    CONSTRAINT "CK_Payments_Method_Range" CHECK ("Method" BETWEEN 1 AND 2),
    CONSTRAINT "CK_Payments_Direction_Range" CHECK ("Direction" BETWEEN 1 AND 2)
);

CREATE TABLE IF NOT EXISTS "Damages" (
    "Id"               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "VehicleId"        integer NOT NULL REFERENCES "Vehicles"("Id") ON DELETE CASCADE,
    "RentalId"         integer NULL REFERENCES "Rentals"("Id") ON DELETE SET NULL,
    "Description"      varchar(500) NOT NULL,
    "DateReported"     timestamptz NOT NULL,
    "RepairCost"       numeric(10,2) NOT NULL,
    "PhotoPath"        varchar(500) NULL,
    "ActNumber"        varchar(60) NOT NULL UNIQUE,
    "ChargedAmount"    numeric(10,2) NOT NULL,
    "IsChargedToClient" boolean NOT NULL,
    "Status"           integer NOT NULL,
    CONSTRAINT "CK_Damages_RepairCost_Positive" CHECK ("RepairCost" > 0),
    CONSTRAINT "CK_Damages_ChargedAmount_NonNegative" CHECK ("ChargedAmount" >= 0),
    CONSTRAINT "CK_Damages_ChargedAmount_LteRepairCost" CHECK ("ChargedAmount" <= "RepairCost"),
    CONSTRAINT "CK_Damages_ChargeFlag_Consistency" CHECK (
        ("IsChargedToClient" AND "ChargedAmount" > 0)
        OR (NOT "IsChargedToClient" AND "ChargedAmount" = 0)
    ),
    CONSTRAINT "CK_Damages_Status_Range" CHECK ("Status" BETWEEN 1 AND 3)
);

CREATE TABLE IF NOT EXISTS "MaintenanceRecords" (
    "Id"                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "VehicleId"         integer NOT NULL REFERENCES "Vehicles"("Id") ON DELETE CASCADE,
    "ServiceDate"       timestamptz NOT NULL,
    "MileageAtService"  integer NOT NULL,
    "Description"       varchar(500) NOT NULL,
    "Cost"              numeric(10,2) NOT NULL,
    "NextServiceMileage" integer NOT NULL,
    CONSTRAINT "CK_MaintenanceRecords_MileageAtService_NonNegative" CHECK ("MileageAtService" >= 0),
    CONSTRAINT "CK_MaintenanceRecords_Cost_NonNegative" CHECK ("Cost" >= 0),
    CONSTRAINT "CK_MaintenanceRecords_NextServiceMileage_Positive" CHECK ("NextServiceMileage" > 0),
    CONSTRAINT "CK_MaintenanceRecords_NextServiceMileage_GteCurrent" CHECK ("NextServiceMileage" >= "MileageAtService")
);

CREATE INDEX IF NOT EXISTS "IX_Rentals_VehicleId_StartDate_EndDate_Status" ON "Rentals" ("VehicleId", "StartDate", "EndDate", "Status");
CREATE INDEX IF NOT EXISTS "IX_Rentals_ClientId_Status" ON "Rentals" ("ClientId", "Status");
CREATE INDEX IF NOT EXISTS "IX_Rentals_EmployeeId_CreatedAtUtc" ON "Rentals" ("EmployeeId", "CreatedAtUtc");
CREATE INDEX IF NOT EXISTS "IX_Employees_Role_IsActive" ON "Employees" ("Role", "IsActive");
CREATE INDEX IF NOT EXISTS "IX_Clients_Phone" ON "Clients" ("Phone");
CREATE INDEX IF NOT EXISTS "IX_Payments_RentalId_CreatedAtUtc" ON "Payments" ("RentalId", "CreatedAtUtc");
CREATE INDEX IF NOT EXISTS "IX_Payments_EmployeeId_CreatedAtUtc" ON "Payments" ("EmployeeId", "CreatedAtUtc");
CREATE INDEX IF NOT EXISTS "IX_Damages_VehicleId_DateReported" ON "Damages" ("VehicleId", "DateReported");
CREATE INDEX IF NOT EXISTS "IX_Damages_RentalId" ON "Damages" ("RentalId");
CREATE INDEX IF NOT EXISTS "IX_MaintenanceRecords_VehicleId_ServiceDate" ON "MaintenanceRecords" ("VehicleId", "ServiceDate");
CREATE INDEX IF NOT EXISTS "IX_Vehicles_IsAvailable_Make_Model" ON "Vehicles" ("IsAvailable", "Make", "Model");
CREATE OR REPLACE FUNCTION sync_vehicle_availability(p_vehicle_id integer)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    IF p_vehicle_id IS NULL THEN
        RETURN;
    END IF;

    UPDATE "Vehicles" AS v
    SET "IsAvailable" = NOT EXISTS (
        SELECT 1
        FROM "Rentals" AS r
        WHERE r."VehicleId" = v."Id"
          AND r."Status" = 2
    )
    WHERE v."Id" = p_vehicle_id;
END;
$$;

CREATE OR REPLACE FUNCTION trg_sync_vehicle_availability()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM sync_vehicle_availability(COALESCE(NEW."VehicleId", OLD."VehicleId"));

    IF TG_OP = 'UPDATE' AND NEW."VehicleId" IS DISTINCT FROM OLD."VehicleId" THEN
        PERFORM sync_vehicle_availability(OLD."VehicleId");
    END IF;

    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_rentals_sync_vehicle_availability ON "Rentals";
CREATE TRIGGER trg_rentals_sync_vehicle_availability
AFTER INSERT OR UPDATE OR DELETE ON "Rentals"
FOR EACH ROW
EXECUTE FUNCTION trg_sync_vehicle_availability();

CREATE OR REPLACE FUNCTION next_contract_number(p_year integer)
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
    v_number integer;
BEGIN
    INSERT INTO "ContractSequences" ("Year", "LastNumber")
    VALUES (p_year, 0)
    ON CONFLICT ("Year") DO NOTHING;

    UPDATE "ContractSequences"
    SET "LastNumber" = "LastNumber" + 1
    WHERE "Year" = p_year
    RETURNING "LastNumber" INTO v_number;

    RETURN format('CR-%s-%06s', p_year, v_number);
END;
$$;
