-- PostgreSQL schema for coursework defense
-- Business schema after the deep redesign
-- Run on an empty database

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS "Accounts" (
    "Id"                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Login"                varchar(60) NOT NULL,
    "PasswordHash"         varchar(512) NOT NULL,
    "IsActive"             boolean NOT NULL DEFAULT TRUE,
    "FailedLoginAttempts"  integer NOT NULL DEFAULT 0,
    "LockoutUntilUtc"      timestamp with time zone NULL,
    "LastLoginUtc"         timestamp with time zone NULL,
    "PasswordChangedAtUtc" timestamp with time zone NOT NULL,
    "CreatedAtUtc"         timestamp with time zone NOT NULL,
    "UpdatedAtUtc"         timestamp with time zone NOT NULL,
    CONSTRAINT "CK_Accounts_FailedLoginAttempts_NonNegative" CHECK ("FailedLoginAttempts" >= 0)
);

CREATE TABLE IF NOT EXISTS "EmployeeRoles" (
    "Id"          integer PRIMARY KEY,
    "DisplayName" varchar(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS "RentalStatuses" (
    "Id"          integer PRIMARY KEY,
    "DisplayName" varchar(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS "PaymentMethods" (
    "Id"          integer PRIMARY KEY,
    "DisplayName" varchar(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS "PaymentDirections" (
    "Id"          integer PRIMARY KEY,
    "DisplayName" varchar(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS "PaymentStatuses" (
    "Id"          integer PRIMARY KEY,
    "DisplayName" varchar(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS "DamageStatuses" (
    "Id"          integer PRIMARY KEY,
    "DisplayName" varchar(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS "InspectionTypes" (
    "Id"          integer PRIMARY KEY,
    "DisplayName" varchar(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS "VehicleStatuses" (
    "Code"        varchar(20) PRIMARY KEY,
    "DisplayName" varchar(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS "ClientDocumentTypes" (
    "Code"        varchar(30) PRIMARY KEY,
    "DisplayName" varchar(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS "MaintenanceTypes" (
    "Code"        varchar(30) PRIMARY KEY,
    "DisplayName" varchar(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS "FuelTypes" (
    "Code"         varchar(30) PRIMARY KEY,
    "DisplayName"  varchar(60) NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "TransmissionTypes" (
    "Code"         varchar(30) PRIMARY KEY,
    "DisplayName"  varchar(60) NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "Employees" (
    "Id"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AccountId"    integer NOT NULL REFERENCES "Accounts"("Id") ON DELETE RESTRICT,
    "FullName"     varchar(120) NOT NULL,
    "Role"         integer NOT NULL REFERENCES "EmployeeRoles"("Id") ON DELETE RESTRICT,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "Clients" (
    "Id"               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AccountId"        integer NULL REFERENCES "Accounts"("Id") ON DELETE RESTRICT,
    "FullName"         varchar(120) NOT NULL,
    "Phone"            varchar(40) NOT NULL,
    "IsBlacklisted"    boolean NOT NULL DEFAULT FALSE,
    "BlacklistReason"  varchar(400) NULL,
    "BlacklistedAtUtc" timestamp with time zone NULL,
    "IsDeleted"        boolean NOT NULL DEFAULT FALSE,
    "CreatedAtUtc"     timestamp with time zone NOT NULL,
    "UpdatedAtUtc"     timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "ClientDocuments" (
    "Id"               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClientId"         integer NOT NULL REFERENCES "Clients"("Id") ON DELETE CASCADE,
    "DocumentTypeCode" varchar(30) NOT NULL REFERENCES "ClientDocumentTypes"("Code") ON DELETE RESTRICT,
    "DocumentNumber"   varchar(120) NOT NULL,
    "ExpirationDate"   date NULL,
    "StoredPath"       varchar(500) NULL,
    "IsDeleted"        boolean NOT NULL DEFAULT FALSE,
    "CreatedAtUtc"     timestamp with time zone NOT NULL,
    "UpdatedAtUtc"     timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "Vehicles" (
    "Id"                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Make"                    varchar(60) NOT NULL,
    "Model"                   varchar(80) NOT NULL,
    "PowertrainCapacityValue" numeric(10,2) NOT NULL,
    "PowertrainCapacityUnit"  varchar(16) NOT NULL,
    "FuelTypeCode"            varchar(30) NOT NULL REFERENCES "FuelTypes"("Code") ON DELETE RESTRICT,
    "TransmissionTypeCode"    varchar(30) NOT NULL REFERENCES "TransmissionTypes"("Code") ON DELETE RESTRICT,
    "VehicleStatusCode"       varchar(20) NOT NULL DEFAULT 'READY' REFERENCES "VehicleStatuses"("Code") ON DELETE RESTRICT,
    "DoorsCount"              integer NOT NULL DEFAULT 4,
    "CargoCapacityValue"      numeric(10,2) NOT NULL,
    "CargoCapacityUnit"       varchar(16) NOT NULL,
    "ConsumptionValue"        numeric(10,2) NOT NULL,
    "ConsumptionUnit"         varchar(24) NOT NULL,
    "HasAirConditioning"      boolean NOT NULL DEFAULT TRUE,
    "LicensePlate"            varchar(30) NOT NULL,
    "Mileage"                 integer NOT NULL,
    "DailyRate"               numeric(10,2) NOT NULL,
    "IsDeleted"               boolean NOT NULL DEFAULT FALSE,
    "ServiceIntervalKm"       integer NOT NULL DEFAULT 10000,
    "CreatedAtUtc"            timestamp with time zone NOT NULL,
    "UpdatedAtUtc"            timestamp with time zone NOT NULL,
    CONSTRAINT "CK_Vehicles_Mileage_NonNegative" CHECK ("Mileage" >= 0),
    CONSTRAINT "CK_Vehicles_DailyRate_Positive" CHECK ("DailyRate" > 0),
    CONSTRAINT "CK_Vehicles_ServiceIntervalKm_Positive" CHECK ("ServiceIntervalKm" > 0),
    CONSTRAINT "CK_Vehicles_DoorsCount_Range" CHECK ("DoorsCount" BETWEEN 1 AND 8),
    CONSTRAINT "CK_Vehicles_PowertrainCapacity_Positive" CHECK ("PowertrainCapacityValue" > 0),
    CONSTRAINT "CK_Vehicles_CargoCapacity_Positive" CHECK ("CargoCapacityValue" > 0),
    CONSTRAINT "CK_Vehicles_Consumption_Positive" CHECK ("ConsumptionValue" > 0),
    CONSTRAINT "CK_Vehicles_PowertrainCapacityUnit_Allowed" CHECK ("PowertrainCapacityUnit" IN ('L', 'KWH')),
    CONSTRAINT "CK_Vehicles_CargoCapacityUnit_Allowed" CHECK ("CargoCapacityUnit" IN ('L', 'KG', 'SEATS')),
    CONSTRAINT "CK_Vehicles_ConsumptionUnit_Allowed" CHECK ("ConsumptionUnit" IN ('L_PER_100KM', 'KWH_PER_100KM'))
);

CREATE TABLE IF NOT EXISTS "VehiclePhotos" (
    "Id"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "VehicleId"    integer NOT NULL REFERENCES "Vehicles"("Id") ON DELETE CASCADE,
    "StoredPath"   varchar(500) NOT NULL,
    "SortOrder"    integer NOT NULL,
    "IsPrimary"    boolean NOT NULL DEFAULT FALSE,
    "CreatedAtUtc" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "Rentals" (
    "Id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClientId"           integer NOT NULL REFERENCES "Clients"("Id") ON DELETE RESTRICT,
    "VehicleId"          integer NOT NULL REFERENCES "Vehicles"("Id") ON DELETE RESTRICT,
    "CreatedByEmployeeId" integer NOT NULL REFERENCES "Employees"("Id") ON DELETE RESTRICT,
    "ClosedByEmployeeId"  integer NULL REFERENCES "Employees"("Id") ON DELETE RESTRICT,
    "CanceledByEmployeeId" integer NULL REFERENCES "Employees"("Id") ON DELETE RESTRICT,
    "ContractNumber"     varchar(40) NOT NULL,
    "StartDate"          timestamp without time zone NOT NULL,
    "EndDate"            timestamp without time zone NOT NULL,
    "PickupLocation"     varchar(80) NOT NULL,
    "ReturnLocation"     varchar(80) NOT NULL,
    "StartMileage"       integer NOT NULL,
    "EndMileage"         integer NULL,
    "OverageFee"         numeric(10,2) NOT NULL,
    "TotalAmount"        numeric(10,2) NOT NULL,
    "Status"             integer NOT NULL REFERENCES "RentalStatuses"("Id") ON DELETE RESTRICT,
    "CreatedAtUtc"       timestamp with time zone NOT NULL,
    "ClosedAtUtc"        timestamp with time zone NULL,
    "CanceledAtUtc"      timestamp with time zone NULL,
    "CancellationReason" varchar(400) NULL,
    CONSTRAINT "AK_Rentals_Id_VehicleId" UNIQUE ("Id", "VehicleId"),
    CONSTRAINT "CK_Rentals_DateRange" CHECK ("StartDate" <= "EndDate"),
    CONSTRAINT "CK_Rentals_StartMileage_NonNegative" CHECK ("StartMileage" >= 0),
    CONSTRAINT "CK_Rentals_EndMileage_Valid" CHECK ("EndMileage" IS NULL OR "EndMileage" >= "StartMileage"),
    CONSTRAINT "CK_Rentals_OverageFee_NonNegative" CHECK ("OverageFee" >= 0),
    CONSTRAINT "CK_Rentals_TotalAmount_NonNegative" CHECK ("TotalAmount" >= 0),
    CONSTRAINT "CK_Rentals_Closed_Lifecycle" CHECK (
        "Status" <> 3
        OR ("ClosedAtUtc" IS NOT NULL AND "CanceledAtUtc" IS NULL AND "CancellationReason" IS NULL)
    ),
    CONSTRAINT "CK_Rentals_Canceled_Lifecycle" CHECK (
        "Status" <> 4
        OR ("ClosedAtUtc" IS NULL AND "CanceledAtUtc" IS NOT NULL AND length(btrim(COALESCE("CancellationReason", ''))) > 0)
    ),
    CONSTRAINT "CK_Rentals_Open_Lifecycle" CHECK (
        "Status" IN (3, 4)
        OR ("ClosedAtUtc" IS NULL AND "CanceledAtUtc" IS NULL AND "CancellationReason" IS NULL)
    )
);

CREATE TABLE IF NOT EXISTS "RentalInspections" (
    "Id"                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RentalId"            integer NOT NULL REFERENCES "Rentals"("Id") ON DELETE CASCADE,
    "PerformedByEmployeeId" integer NOT NULL REFERENCES "Employees"("Id") ON DELETE RESTRICT,
    "Type"                integer NOT NULL REFERENCES "InspectionTypes"("Id") ON DELETE RESTRICT,
    "CompletedAtUtc"      timestamp with time zone NOT NULL,
    "FuelPercent"         integer NULL,
    "Notes"               varchar(500) NULL,
    "CreatedAtUtc"        timestamp with time zone NOT NULL,
    "UpdatedAtUtc"        timestamp with time zone NOT NULL,
    CONSTRAINT "CK_RentalInspections_FuelPercent_Range" CHECK ("FuelPercent" IS NULL OR "FuelPercent" BETWEEN 0 AND 100)
);

CREATE TABLE IF NOT EXISTS "Payments" (
    "Id"                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RentalId"              integer NOT NULL REFERENCES "Rentals"("Id") ON DELETE CASCADE,
    "EmployeeId"            integer NOT NULL REFERENCES "Employees"("Id") ON DELETE RESTRICT,
    "Amount"                numeric(10,2) NOT NULL,
    "Method"                integer NOT NULL REFERENCES "PaymentMethods"("Id") ON DELETE RESTRICT,
    "Direction"             integer NOT NULL REFERENCES "PaymentDirections"("Id") ON DELETE RESTRICT,
    "Status"                integer NOT NULL REFERENCES "PaymentStatuses"("Id") ON DELETE RESTRICT,
    "CreatedAtUtc"          timestamp with time zone NOT NULL,
    "Notes"                 varchar(300) NULL,
    "ExternalTransactionId" varchar(120) NULL,
    CONSTRAINT "CK_Payments_Amount_Positive" CHECK ("Amount" > 0)
);

CREATE TABLE IF NOT EXISTS "Damages" (
    "Id"                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "VehicleId"            integer NOT NULL REFERENCES "Vehicles"("Id") ON DELETE CASCADE,
    "RentalId"             integer NULL,
    "ReportedByEmployeeId" integer NOT NULL REFERENCES "Employees"("Id") ON DELETE RESTRICT,
    "Description"          varchar(500) NOT NULL,
    "DateReported"         timestamp without time zone NOT NULL,
    "RepairCost"           numeric(10,2) NOT NULL,
    "ActNumber"            varchar(60) NOT NULL,
    "ChargedAmount"        numeric(10,2) NOT NULL,
    "Status"               integer NOT NULL REFERENCES "DamageStatuses"("Id") ON DELETE RESTRICT,
    "CreatedAtUtc"         timestamp with time zone NOT NULL,
    "UpdatedAtUtc"         timestamp with time zone NOT NULL,
    CONSTRAINT "CK_Damages_RepairCost_Positive" CHECK ("RepairCost" > 0),
    CONSTRAINT "CK_Damages_ChargedAmount_NonNegative" CHECK ("ChargedAmount" >= 0),
    CONSTRAINT "CK_Damages_ChargedAmount_LteRepairCost" CHECK ("ChargedAmount" <= "RepairCost"),
    CONSTRAINT "CK_Damages_Status_ChargeConsistency" CHECK (
        ("Status" <> 1 OR "ChargedAmount" = 0)
        AND ("Status" <> 2 OR "ChargedAmount" > 0)
    ),
    CONSTRAINT "FK_Damages_Rentals_RentalId_VehicleId" FOREIGN KEY ("RentalId", "VehicleId")
        REFERENCES "Rentals" ("Id", "VehicleId") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "DamagePhotos" (
    "Id"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DamageId"     integer NOT NULL REFERENCES "Damages"("Id") ON DELETE CASCADE,
    "StoredPath"   varchar(500) NOT NULL,
    "SortOrder"    integer NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "MaintenanceRecords" (
    "Id"                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "VehicleId"           integer NOT NULL REFERENCES "Vehicles"("Id") ON DELETE CASCADE,
    "PerformedByEmployeeId" integer NULL REFERENCES "Employees"("Id") ON DELETE RESTRICT,
    "ServiceDate"         timestamp without time zone NOT NULL,
    "MileageAtService"    integer NOT NULL,
    "Description"         varchar(500) NOT NULL,
    "Cost"                numeric(10,2) NOT NULL,
    "NextServiceMileage"  integer NOT NULL,
    "MaintenanceTypeCode" varchar(30) NOT NULL REFERENCES "MaintenanceTypes"("Code") ON DELETE RESTRICT,
    "ServiceProviderName" varchar(160) NULL,
    CONSTRAINT "CK_MaintenanceRecords_MileageAtService_NonNegative" CHECK ("MileageAtService" >= 0),
    CONSTRAINT "CK_MaintenanceRecords_Cost_NonNegative" CHECK ("Cost" >= 0),
    CONSTRAINT "CK_MaintenanceRecords_NextServiceMileage_GteCurrent" CHECK ("NextServiceMileage" >= "MileageAtService")
);

-- Technical helper table, excluded from defense ER diagrams
CREATE TABLE IF NOT EXISTS "ContractSequences" (
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Year"       integer NOT NULL,
    "LastNumber" integer NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Accounts_Login" ON "Accounts" ("Login");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Employees_AccountId" ON "Employees" ("AccountId");
CREATE INDEX IF NOT EXISTS "IX_Employees_Role_FullName" ON "Employees" ("Role", "FullName");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Clients_AccountId" ON "Clients" ("AccountId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Clients_Phone" ON "Clients" ("Phone") WHERE "IsDeleted" = FALSE;
CREATE INDEX IF NOT EXISTS "IX_Clients_IsDeleted" ON "Clients" ("IsDeleted");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_ClientDocuments_ClientId_DocumentTypeCode"
    ON "ClientDocuments" ("ClientId", "DocumentTypeCode") WHERE "IsDeleted" = FALSE;
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ClientDocuments_DocumentTypeCode_DocumentNumber"
    ON "ClientDocuments" ("DocumentTypeCode", "DocumentNumber") WHERE "IsDeleted" = FALSE;

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Vehicles_LicensePlate" ON "Vehicles" ("LicensePlate") WHERE "IsDeleted" = FALSE;
CREATE INDEX IF NOT EXISTS "IX_Vehicles_VehicleStatusCode_Make_Model" ON "Vehicles" ("VehicleStatusCode", "Make", "Model");
CREATE INDEX IF NOT EXISTS "IX_Vehicles_IsDeleted" ON "Vehicles" ("IsDeleted");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_VehiclePhotos_VehicleId_SortOrder" ON "VehiclePhotos" ("VehicleId", "SortOrder");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Rentals_ContractNumber" ON "Rentals" ("ContractNumber");
CREATE INDEX IF NOT EXISTS "IX_Rentals_VehicleId_StartDate_EndDate_Status" ON "Rentals" ("VehicleId", "StartDate", "EndDate", "Status");
CREATE INDEX IF NOT EXISTS "IX_Rentals_ClientId_Status" ON "Rentals" ("ClientId", "Status");
CREATE INDEX IF NOT EXISTS "IX_Rentals_CreatedByEmployeeId_CreatedAtUtc" ON "Rentals" ("CreatedByEmployeeId", "CreatedAtUtc");
CREATE INDEX IF NOT EXISTS "IX_Rentals_CreatedAtUtc" ON "Rentals" ("CreatedAtUtc");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_RentalInspections_RentalId_Type" ON "RentalInspections" ("RentalId", "Type");

CREATE INDEX IF NOT EXISTS "IX_Payments_RentalId_CreatedAtUtc" ON "Payments" ("RentalId", "CreatedAtUtc");
CREATE INDEX IF NOT EXISTS "IX_Payments_EmployeeId_CreatedAtUtc" ON "Payments" ("EmployeeId", "CreatedAtUtc");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Payments_ExternalTransactionId" ON "Payments" ("ExternalTransactionId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Damages_ActNumber" ON "Damages" ("ActNumber");
CREATE INDEX IF NOT EXISTS "IX_Damages_VehicleId_DateReported" ON "Damages" ("VehicleId", "DateReported");
CREATE INDEX IF NOT EXISTS "IX_Damages_RentalId" ON "Damages" ("RentalId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_DamagePhotos_DamageId_SortOrder" ON "DamagePhotos" ("DamageId", "SortOrder");

CREATE INDEX IF NOT EXISTS "IX_MaintenanceRecords_VehicleId_ServiceDate" ON "MaintenanceRecords" ("VehicleId", "ServiceDate");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ContractSequences_Year" ON "ContractSequences" ("Year");

ALTER TABLE "Rentals"
DROP CONSTRAINT IF EXISTS "EX_Rentals_NoOverlappingActiveOrBookedPeriods";

ALTER TABLE "Rentals"
ADD CONSTRAINT "EX_Rentals_NoOverlappingActiveOrBookedPeriods"
EXCLUDE USING gist (
    "VehicleId" WITH =,
    tsrange("StartDate", "EndDate", '[]') WITH &&
)
WHERE ("Status" IN (1, 2));

CREATE OR REPLACE FUNCTION next_contract_number(p_year integer)
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
    v_number integer;
BEGIN
    INSERT INTO "ContractSequences" ("Year", "LastNumber")
    VALUES (p_year, 0)
    ON CONFLICT ("Year") DO NOTHING;

    UPDATE "ContractSequences"
    SET "LastNumber" = "LastNumber" + 1
    WHERE "Year" = p_year
    RETURNING "LastNumber" INTO v_number;

    RETURN format('CR-%s-%06s', p_year, v_number);
END;
$$;
